const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const GET_GITHUB_USERS = 'GET_GITHUB_USERS'
const SET_GITHUB_USERS = 'SET_GITHUB_USERS'

const GET_GITHUB_USER_DETAIL = 'GET_GITHUB_USER_DETAIL'
const SET_GITHUB_USER_DETAIL = 'SET_GITHUB_USER_DETAIL'


export {  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  GET_GITHUB_USERS,
  SET_GITHUB_USERS,
  GET_GITHUB_USER_DETAIL,
  SET_GITHUB_USER_DETAIL
};
